# Generated by Django 5.2.15 on 2026-07-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_backfill_wow_lifecycle_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywowpacket',
            name='author_id',
        ),
    ]
