# Generated by Django 5.2.15 on 2026-07-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_remove_dailywowpacket_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywowpacket',
            name='format_version',
            field=models.CharField(default='wow_packet_v0.2', max_length=64),
        ),
    ]
